# Generated by Django 5.0.3 on 2024-06-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor_info',
            fields=[
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('professor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=200)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=2)),
                ('student_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
