# Generated by Django 5.0.3 on 2024-06-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor_info',
            name='password',
            field=models.CharField(default='default_password', max_length=255),
        ),
        migrations.AddField(
            model_name='student_info',
            name='password',
            field=models.CharField(default='default_password', max_length=255),
        ),
    ]
