# Generated by Django 5.0.3 on 2024-06-27 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_professor_info_password_student_info_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='professor_class_mapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_stud', models.CharField(max_length=2)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.professor_info')),
            ],
        ),
    ]
