# Generated by Django 5.0.3 on 2024-06-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_professor_class_mapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='professor_sub_mapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.professor_info')),
            ],
        ),
    ]
