# Generated by Django 5.0.3 on 2024-07-03 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_professor_sub_mapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsa', models.CharField(max_length=3)),
                ('os', models.CharField(max_length=3)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.student_info')),
            ],
        ),
    ]
