# Generated by Django 5.0.3 on 2024-07-04 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_studentmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_dsa', models.CharField(blank=True, max_length=3, null=True)),
                ('attendance_os', models.CharField(blank=True, max_length=3, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.student_info')),
            ],
        ),
    ]
