# Generated by Django 5.0.3 on 2024-07-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_studentattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
